### PR TITLE
optimize worldgen, add support for deobfuscated environments, fix 1.7.2 leftovers

### PR DESCRIPTION
**Pull request by asiekierka**

### CODE REVIEW

**Comment by Zeno410** [comment]
Thanks very much for the direct EBS references. How much of a difference do they make?

Since you changed Accessor to be a different routine, could you please give your routine a different name? I use it (in other mods) for multiple fields in the same class with the same class.

The Highlands double routine was because, at the time, the Forge obfuscator didn't obfuscate the name. So, to work, there had to be one copy with the deobfuscated name (for the compiler to accept it) and one with the obfuscated name (to actually run.) Have you tested this in an obfuscated environment?

**Comment by Zeno410** [comment]
On second thought, never mind about rewriting Accessor. I can rewrite the class to accomodate both constructors.

**Comment by asiekierka** [comment]
>Thanks very much for the direct EBS references. How much of a difference do they make?

Up to 5-6 times faster. Yes, I actually tested it.

>Have you tested this in an obfuscated environment?

Not with Highlands, however the code would not compile otherwise.

>On second thought, never mind about rewriting Accessor. I can rewrite the class to accomodate both constructors.

That would be a good idea indeed, though I believe the String variant should be deprecated, especially on obfuscated names. Possibly a double-String variant. You might want to just copy over the EBS changes, those are key.

**Comment by Zeno410** [comment]
Yes, as before, it needs the obfuscated code in the decorators to place the UB stones in those Highlands biomes.

**Pull request merged**
